# This workflow will run the tests.

name: Run Tests & build

on: [pull_request, workflow_dispatch]

jobs:
  build & test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Use Node with nvm
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - run: npm install
    - run: npm run lint
    - run: npm run prettier
    - run: npm run sassdoc
    - run: npm run build
    - run: npm run test
    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.0.0
