# This workflow will run the tests.

name: Run Tests

on: [pull_request, workflow_dispatch]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node
      uses: actions/setup-node@v3
      with:
        node-version: '14.17.5'
    - run: npm install
    - run: npm run test
