# This workflow will run the tests.

name: Run Tests & build

on: [pull_request, workflow_dispatch]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvm
    - name: Use Node with nvm
      uses: actions/setup-node@v3
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'
    - run: npm install
    - run: npm run test
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvm
    - name: Use Node with nvm
      uses: actions/setup-node@v3
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'
    - run: npm install
    - run: npm run lint
    - run: npm run prettier
    - run: npm run sassdoc
    - run: npm run build
    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.0.0
